version: '3'
volumes:
  redis-data:
  db-postgres:

services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data

  db:
    image: postgres:12.0-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data


