development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/1" %>
  channel_prefix: last_ubication_vehicle_production
