# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
   # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Docker Hub image that `container-job` executes in
    container: rudolfaraya/rails-base-ruby253
    services:
      db:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: admin_test
          POSTGRES_USER: admin_test
          POSTGRES_DATABASE: last_ubication_development
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5  
      redis:
        image: redis

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.110.0
#        with:
#          ruby-version: 2.5.3

      - name: Install Dependencies
        run: |
          gem update --system 3.2.3
          gem install bundler -v 2.3.5
          bundle config build.nokogiri --use-system-libraries
          yarn install --check-files --ignore-engines
      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        run: |
          bundle exec rails db:prepare
        env:
          POSTGRES_PASSWORD: admin_test
          POSTGRES_USER: admin_test
          POSTGRES_DATABASE: last_ubication_development
          POSTGRES_HOST: database

      - name: Run Tests
        run: |
          bundle exec rails rspec
